### ISSUE TITLE
接続先のPeerCastをデフォルトに戻せない

### ISSUE THREAD

**Issue by plonk** [shule517/peca-live#39]
設定ダイアログからカスタムの接続先として localhost:7144 を指定して保存したあと、[デフォルトに戻す]→[保存]してもlocalStorageが変更されず、ページをリロードすると localhost:7144 に戻ってしまいます。

https://github.com/shule517/peca-live/commit/638b8807086f0025dbd2aa2937ce6f055b9087b6
このコミットで、設定された値がそれぞれデフォルト値と同じだった場合はストレージの内容を変更しないようになっているのですが、本来は removeItem するべきかと。

**Comment by shule517** [comment]
よてさんのコメントの通り、「デフォルトに戻す」場合はremoveItemが正しそう！
「デフォルトに戻す」→「保存」 ではなく、１クリックで良さそう！
